name: Build Docker Image and Run Tests

on:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      repo:
        description: 'owner/repo'
        required: true
      commit:
        description: 'SHA'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 检出目标仓库的特定提交
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.commit }}

      # 生成 Dockerfile
      - name: Generate Dockerfile
        run: |
          cat <<EOF > Dockerfile
          # 使用 Python 基础镜像，你可以根据实际需求调整版本
          FROM python:3.11
          # 设置工作目录
          WORKDIR /app
          # 复制项目代码到工作目录
          COPY . .
          # 创建并激活虚拟环境，安装依赖项
          RUN python -m venv venv && \
              /bin/bash -c "source venv/bin/activate && \
              cd django-repo/tests && \
              python -m pip install -e .. && \
              python -m pip install -r requirements/py3.txt"
          # 运行测试脚本
          CMD ["/bin/bash", "-c", "source venv/bin/activate && cd django-repo/tests && ./runtests.py"]
          EOF
      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t my-test-image .

      # 运行 Docker 容器，创建虚拟环境，安装依赖并运行测试
      - name: run tests in Docker
        run: |
          docker run -it --name test-container my-test-image 